### ISSUE TITLE
Exposure issue?

### ISSUE THREAD

**Issue by ATSmith333** [tangrams/heightmapper#35]
Is anyone able to get height maps right now?  Manual min/max elevation gives no results, while auto-exposure gives a rolling number in the zx scale, with just a plain white screen.

**Comment by AlexandrZhigalin** [comment]
No, it has nothing to do with exposure settings; i've described the issue [here](https://github.com/tangrams/heightmapper/pull/34/commits/606c9deddec82974f2232d51d9569ee80229b110).

**Comment by meetar** [comment]
This should be resolved, thanks for your patience!

**Comment by AlexandrZhigalin** [comment]
@ATSmith333 , type this in the browser console within your opened session: 
`layer.scene.sources.elevation.url = 'https://s3.amazonaws.com/elevation-tiles-prod/terrarium/{z}/{x}/{y}.png';`

**Comment by ATSmith333** [comment]
Superb!  Much appreciated!

**Comment by ATSmith333** [comment]
It was working fine yesterday but looks like the problem is back when zooming in?

**Comment by meetar** [comment]
Looking okay here, might have just taken a little while for all the tiles to come back – if you still see any problem areas, feel free to paste links below and we'll check it out!
